# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.19.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/test

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Slack Notification [START]
          command: |
            if [ -z $SLACK_WEBHOOK ];then echo "SLACK_WEBHOOK is not configured.";else curl $SLACK_WEBHOOK \
            -s \
            -X POST \
            -H "Content-Type: application/json" \
            -d "{ \"text\": \":arrow_forward: ${CIRCLE_BRANCH} of https://circleci.com/gh/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}\n> COVERAGE: *$(curl https://codecov.io/gh/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/branch/master/graph/badge.txt)%* https://codecov.io/gh/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}\n> STATUS: https://circleci.com/gh/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.png?r=$(cat /dev/urandom | base64 | fold -w 10 | head -n 1)\" }";fi

      - run: curl -o- -L https://yarnpkg.com/install.sh | bash

      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "./yarn.lock" }}
            - yarn-packages-{{ checksum "./express/yarn.lock" }}
            - yarn-packages-{{ checksum "./vue/yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - yarn-packages-

      - run: yarn install --frozen-lockfile

      - run: cd ./express && yarn install --frozen-lockfile

      - run: cd ./vue && yarn install --frozen-lockfile

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-{{ checksum "yarn.lock" }}

      - save_cache:
          paths:
            - ~/.cache/express/yarn
          key: yarn-packages-{{ checksum "./express/yarn.lock" }}

      - save_cache:
          paths:
            - ~/.cache/vue/yarn
          key: yarn-packages-{{ checksum "./vue/yarn.lock" }}

      - run: yarn dokku:in && yarn sqlite:on

      - run: yarn lint-code-express

      - run: yarn lint-code-vue

      - run: DOKKU_IN=true SQLITE=true yarn migrate

      - run: DOKKU_IN=true SQLITE=true yarn build-express

      - run: yarn build-vue

      - run: yarn test-express

      - run: yarn test-vue

      - run: if [ -z $CODECOV_TOKEN ];then echo "CODECOV_TOKEN is not configured.";else yarn codecov-vue --token=$CODECOV_TOKEN;fi

      - run: if [ -z $CODECOV_TOKEN ];then echo "CODECOV_TOKEN is not configured.";else yarn codecov-express --token=$CODECOV_TOKEN;fi

      - run:
          name: Slack Notification [FINISH]
          command: |
            if [ -z $SLACK_WEBHOOK ];then echo "SLACK_WEBHOOK is not configured.";else curl $SLACK_WEBHOOK \
            -s \
            -X POST \
            -H "Content-Type: application/json" \
            -d "{ \"text\": \":tada: ${CIRCLE_BRANCH} of https://circleci.com/gh/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}\n> COVERAGE: *$(sleep 3 && curl https://codecov.io/gh/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/branch/master/graph/badge.txt)%* https://codecov.io/gh/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}\n> STATUS: https://circleci.com/gh/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.png?r=$(cat /dev/urandom | base64 | fold -w 10 | head -n 1)\" }";fi

      - run:
          name: Slack Notification [ERROR]
          command: |
            if [ -z $SLACK_WEBHOOK ];then echo "SLACK_WEBHOOK is not configured.";else curl $SLACK_WEBHOOK \
            -s \
            -X POST \
            -H "Content-Type: application/json" \
            -d "{ \"text\": \":boom: ${CIRCLE_BRANCH} of https://circleci.com/gh/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}\n> COVERAGE: *$(curl https://codecov.io/gh/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/branch/master/graph/badge.txt)%* https://codecov.io/gh/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}\n> STATUS: https://circleci.com/gh/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.png?r=$(cat /dev/urandom | base64 | fold -w 10 | head -n 1)\" }";fi
          when: on_fail
